// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// GetAuthenticatedUserOKCode is the HTTP code returned for type GetAuthenticatedUserOK
const GetAuthenticatedUserOKCode int = 200

/*GetAuthenticatedUserOK Return the account of the authenticated user

swagger:response getAuthenticatedUserOK
*/
type GetAuthenticatedUserOK struct {

	/*
	  In: Body
	*/
	Payload *GetAuthenticatedUserOKBody `json:"body,omitempty"`
}

// NewGetAuthenticatedUserOK creates GetAuthenticatedUserOK with default headers values
func NewGetAuthenticatedUserOK() *GetAuthenticatedUserOK {

	return &GetAuthenticatedUserOK{}
}

// WithPayload adds the payload to the get authenticated user o k response
func (o *GetAuthenticatedUserOK) WithPayload(payload *GetAuthenticatedUserOKBody) *GetAuthenticatedUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get authenticated user o k response
func (o *GetAuthenticatedUserOK) SetPayload(payload *GetAuthenticatedUserOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetAuthenticatedUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// GetAuthenticatedUserUnauthorizedCode is the HTTP code returned for type GetAuthenticatedUserUnauthorized
const GetAuthenticatedUserUnauthorizedCode int = 401

/*GetAuthenticatedUserUnauthorized Invalid token

swagger:response getAuthenticatedUserUnauthorized
*/
type GetAuthenticatedUserUnauthorized struct {
}

// NewGetAuthenticatedUserUnauthorized creates GetAuthenticatedUserUnauthorized with default headers values
func NewGetAuthenticatedUserUnauthorized() *GetAuthenticatedUserUnauthorized {

	return &GetAuthenticatedUserUnauthorized{}
}

// WriteResponse to the client
func (o *GetAuthenticatedUserUnauthorized) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(401)
}
