// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// RegisterNewUserOKCode is the HTTP code returned for type RegisterNewUserOK
const RegisterNewUserOKCode int = 200

/*RegisterNewUserOK Account created

swagger:response registerNewUserOK
*/
type RegisterNewUserOK struct {

	/*
	  In: Body
	*/
	Payload *RegisterNewUserOKBody `json:"body,omitempty"`
}

// NewRegisterNewUserOK creates RegisterNewUserOK with default headers values
func NewRegisterNewUserOK() *RegisterNewUserOK {

	return &RegisterNewUserOK{}
}

// WithPayload adds the payload to the register new user o k response
func (o *RegisterNewUserOK) WithPayload(payload *RegisterNewUserOKBody) *RegisterNewUserOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the register new user o k response
func (o *RegisterNewUserOK) SetPayload(payload *RegisterNewUserOKBody) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *RegisterNewUserOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// RegisterNewUserBadRequestCode is the HTTP code returned for type RegisterNewUserBadRequest
const RegisterNewUserBadRequestCode int = 400

/*RegisterNewUserBadRequest Email already registered or invalid input

swagger:response registerNewUserBadRequest
*/
type RegisterNewUserBadRequest struct {
}

// NewRegisterNewUserBadRequest creates RegisterNewUserBadRequest with default headers values
func NewRegisterNewUserBadRequest() *RegisterNewUserBadRequest {

	return &RegisterNewUserBadRequest{}
}

// WriteResponse to the client
func (o *RegisterNewUserBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// RegisterNewUserUnprocessableEntityCode is the HTTP code returned for type RegisterNewUserUnprocessableEntity
const RegisterNewUserUnprocessableEntityCode int = 422

/*RegisterNewUserUnprocessableEntity Missing required fields

swagger:response registerNewUserUnprocessableEntity
*/
type RegisterNewUserUnprocessableEntity struct {
}

// NewRegisterNewUserUnprocessableEntity creates RegisterNewUserUnprocessableEntity with default headers values
func NewRegisterNewUserUnprocessableEntity() *RegisterNewUserUnprocessableEntity {

	return &RegisterNewUserUnprocessableEntity{}
}

// WriteResponse to the client
func (o *RegisterNewUserUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
