// Code generated by go-swagger; DO NOT EDIT.

package auth

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"
	validate "github.com/go-openapi/validate"

	models "github.com/wunari/easypoll-backend/models"
)

// RegisterNewUserHandlerFunc turns a function with the right signature into a register new user handler
type RegisterNewUserHandlerFunc func(RegisterNewUserParams) middleware.Responder

// Handle executing the request and returning a response
func (fn RegisterNewUserHandlerFunc) Handle(params RegisterNewUserParams) middleware.Responder {
	return fn(params)
}

// RegisterNewUserHandler interface for that can handle valid register new user params
type RegisterNewUserHandler interface {
	Handle(RegisterNewUserParams) middleware.Responder
}

// NewRegisterNewUser creates a new http.Handler for the register new user operation
func NewRegisterNewUser(ctx *middleware.Context, handler RegisterNewUserHandler) *RegisterNewUser {
	return &RegisterNewUser{Context: ctx, Handler: handler}
}

/*RegisterNewUser swagger:route POST /register auth registerNewUser

Create a new account

Create a new account and returns a token to be used in requests

*/
type RegisterNewUser struct {
	Context *middleware.Context
	Handler RegisterNewUserHandler
}

func (o *RegisterNewUser) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewRegisterNewUserParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// RegisterNewUserBody register new user body
// swagger:model RegisterNewUserBody
type RegisterNewUserBody struct {

	// Email of the account
	// Required: true
	Email *string `json:"email"`

	// Name of the user
	// Required: true
	Name *string `json:"name"`

	// Password of the account
	// Required: true
	// Format: password
	Password *strfmt.Password `json:"password"`
}

// Validate validates this register new user body
func (o *RegisterNewUserBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateEmail(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validatePassword(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RegisterNewUserBody) validateEmail(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"email", "body", o.Email); err != nil {
		return err
	}

	return nil
}

func (o *RegisterNewUserBody) validateName(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"name", "body", o.Name); err != nil {
		return err
	}

	return nil
}

func (o *RegisterNewUserBody) validatePassword(formats strfmt.Registry) error {

	if err := validate.Required("body"+"."+"password", "body", o.Password); err != nil {
		return err
	}

	if err := validate.FormatOf("body"+"."+"password", "body", "password", o.Password.String(), formats); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RegisterNewUserBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RegisterNewUserBody) UnmarshalBinary(b []byte) error {
	var res RegisterNewUserBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

// RegisterNewUserOKBody register new user o k body
// swagger:model RegisterNewUserOKBody
type RegisterNewUserOKBody struct {
	models.Token

	// user
	User *models.User `json:"user,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *RegisterNewUserOKBody) UnmarshalJSON(raw []byte) error {
	// RegisterNewUserOKBodyAO0
	var registerNewUserOKBodyAO0 models.Token
	if err := swag.ReadJSON(raw, &registerNewUserOKBodyAO0); err != nil {
		return err
	}
	o.Token = registerNewUserOKBodyAO0

	// RegisterNewUserOKBodyAO1
	var dataRegisterNewUserOKBodyAO1 struct {
		User *models.User `json:"user,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataRegisterNewUserOKBodyAO1); err != nil {
		return err
	}

	o.User = dataRegisterNewUserOKBodyAO1.User

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o RegisterNewUserOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	registerNewUserOKBodyAO0, err := swag.WriteJSON(o.Token)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, registerNewUserOKBodyAO0)

	var dataRegisterNewUserOKBodyAO1 struct {
		User *models.User `json:"user,omitempty"`
	}

	dataRegisterNewUserOKBodyAO1.User = o.User

	jsonDataRegisterNewUserOKBodyAO1, errRegisterNewUserOKBodyAO1 := swag.WriteJSON(dataRegisterNewUserOKBodyAO1)
	if errRegisterNewUserOKBodyAO1 != nil {
		return nil, errRegisterNewUserOKBodyAO1
	}
	_parts = append(_parts, jsonDataRegisterNewUserOKBodyAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this register new user o k body
func (o *RegisterNewUserOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.Token
	if err := o.Token.Validate(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateUser(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *RegisterNewUserOKBody) validateUser(formats strfmt.Registry) error {

	if swag.IsZero(o.User) { // not required
		return nil
	}

	if o.User != nil {
		if err := o.User.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("registerNewUserOK" + "." + "user")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *RegisterNewUserOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *RegisterNewUserOKBody) UnmarshalBinary(b []byte) error {
	var res RegisterNewUserOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
