// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	errors "github.com/go-openapi/errors"
	middleware "github.com/go-openapi/runtime/middleware"
	strfmt "github.com/go-openapi/strfmt"
	swag "github.com/go-openapi/swag"

	models "github.com/wunari/easypoll-backend/docs/models"
)

// CreatePollHandlerFunc turns a function with the right signature into a create poll handler
type CreatePollHandlerFunc func(CreatePollParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePollHandlerFunc) Handle(params CreatePollParams) middleware.Responder {
	return fn(params)
}

// CreatePollHandler interface for that can handle valid create poll params
type CreatePollHandler interface {
	Handle(CreatePollParams) middleware.Responder
}

// NewCreatePoll creates a new http.Handler for the create poll operation
func NewCreatePoll(ctx *middleware.Context, handler CreatePollHandler) *CreatePoll {
	return &CreatePoll{Context: ctx, Handler: handler}
}

/*CreatePoll swagger:route POST /polls poll createPoll

Create a new poll

Inserts a new poll in the database

*/
type CreatePoll struct {
	Context *middleware.Context
	Handler CreatePollHandler
}

func (o *CreatePoll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatePollParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}

// CreatePollBody create poll body
// swagger:model CreatePollBody
type CreatePollBody struct {
	models.PollRequest
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *CreatePollBody) UnmarshalJSON(raw []byte) error {
	// CreatePollParamsBodyAO0
	var createPollParamsBodyAO0 models.PollRequest
	if err := swag.ReadJSON(raw, &createPollParamsBodyAO0); err != nil {
		return err
	}
	o.PollRequest = createPollParamsBodyAO0

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o CreatePollBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	createPollParamsBodyAO0, err := swag.WriteJSON(o.PollRequest)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, createPollParamsBodyAO0)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this create poll body
func (o *CreatePollBody) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with models.PollRequest
	if err := o.PollRequest.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (o *CreatePollBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *CreatePollBody) UnmarshalBinary(b []byte) error {
	var res CreatePollBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
