// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// CreatePollHandlerFunc turns a function with the right signature into a create poll handler
type CreatePollHandlerFunc func(CreatePollParams) middleware.Responder

// Handle executing the request and returning a response
func (fn CreatePollHandlerFunc) Handle(params CreatePollParams) middleware.Responder {
	return fn(params)
}

// CreatePollHandler interface for that can handle valid create poll params
type CreatePollHandler interface {
	Handle(CreatePollParams) middleware.Responder
}

// NewCreatePoll creates a new http.Handler for the create poll operation
func NewCreatePoll(ctx *middleware.Context, handler CreatePollHandler) *CreatePoll {
	return &CreatePoll{Context: ctx, Handler: handler}
}

/*CreatePoll swagger:route POST /polls poll createPoll

Creates a new poll

*/
type CreatePoll struct {
	Context *middleware.Context
	Handler CreatePollHandler
}

func (o *CreatePoll) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewCreatePollParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
