// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"io"
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/runtime/middleware"

	models "github.com/wunari/easypoll/docs/models"
)

// NewCreatePollParams creates a new CreatePollParams object
// no default values defined in spec.
func NewCreatePollParams() CreatePollParams {

	return CreatePollParams{}
}

// CreatePollParams contains all the bound params for the create poll operation
// typically these are obtained from a http.Request
//
// swagger:parameters createPoll
type CreatePollParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*Poll object that needs to be added to the database
	  Required: true
	  In: body
	*/
	Body *models.Poll
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewCreatePollParams() beforehand.
func (o *CreatePollParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	if runtime.HasBody(r) {
		defer r.Body.Close()
		var body models.Poll
		if err := route.Consumer.Consume(r.Body, &body); err != nil {
			if err == io.EOF {
				res = append(res, errors.Required("body", "body"))
			} else {
				res = append(res, errors.NewParseError("body", "body", "", err))
			}
		} else {
			// validate body object
			if err := body.Validate(route.Formats); err != nil {
				res = append(res, err)
			}

			if len(res) == 0 {
				o.Body = &body
			}
		}
	} else {
		res = append(res, errors.Required("body", "body"))
	}
	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
