// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"
)

// DeletePollByIDNoContentCode is the HTTP code returned for type DeletePollByIDNoContent
const DeletePollByIDNoContentCode int = 204

/*DeletePollByIDNoContent Poll deleted

swagger:response deletePollByIdNoContent
*/
type DeletePollByIDNoContent struct {
}

// NewDeletePollByIDNoContent creates DeletePollByIDNoContent with default headers values
func NewDeletePollByIDNoContent() *DeletePollByIDNoContent {

	return &DeletePollByIDNoContent{}
}

// WriteResponse to the client
func (o *DeletePollByIDNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// DeletePollByIDNotFoundCode is the HTTP code returned for type DeletePollByIDNotFound
const DeletePollByIDNotFoundCode int = 404

/*DeletePollByIDNotFound Resource not found

swagger:response deletePollByIdNotFound
*/
type DeletePollByIDNotFound struct {
}

// NewDeletePollByIDNotFound creates DeletePollByIDNotFound with default headers values
func NewDeletePollByIDNotFound() *DeletePollByIDNotFound {

	return &DeletePollByIDNotFound{}
}

// WriteResponse to the client
func (o *DeletePollByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}
