// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	middleware "github.com/go-openapi/runtime/middleware"
)

// DeletePollByIDHandlerFunc turns a function with the right signature into a delete poll by Id handler
type DeletePollByIDHandlerFunc func(DeletePollByIDParams) middleware.Responder

// Handle executing the request and returning a response
func (fn DeletePollByIDHandlerFunc) Handle(params DeletePollByIDParams) middleware.Responder {
	return fn(params)
}

// DeletePollByIDHandler interface for that can handle valid delete poll by Id params
type DeletePollByIDHandler interface {
	Handle(DeletePollByIDParams) middleware.Responder
}

// NewDeletePollByID creates a new http.Handler for the delete poll by Id operation
func NewDeletePollByID(ctx *middleware.Context, handler DeletePollByIDHandler) *DeletePollByID {
	return &DeletePollByID{Context: ctx, Handler: handler}
}

/*DeletePollByID swagger:route DELETE /polls/{id} poll deletePollById

Delete a poll by id

*/
type DeletePollByID struct {
	Context *middleware.Context
	Handler DeletePollByIDHandler
}

func (o *DeletePollByID) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		r = rCtx
	}
	var Params = NewDeletePollByIDParams()

	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request

	o.Context.Respond(rw, r, route.Produces, route, res)

}
