// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/wunari/easypoll-backend/docs/models"
)

// GetPollsOKCode is the HTTP code returned for type GetPollsOK
const GetPollsOKCode int = 200

/*GetPollsOK Returns an array of polls

swagger:response getPollsOK
*/
type GetPollsOK struct {

	/*
	  In: Body
	*/
	Payload []*models.Poll `json:"body,omitempty"`
}

// NewGetPollsOK creates GetPollsOK with default headers values
func NewGetPollsOK() *GetPollsOK {

	return &GetPollsOK{}
}

// WithPayload adds the payload to the get polls o k response
func (o *GetPollsOK) WithPayload(payload []*models.Poll) *GetPollsOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get polls o k response
func (o *GetPollsOK) SetPayload(payload []*models.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetPollsOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	payload := o.Payload
	if payload == nil {
		// return empty array
		payload = make([]*models.Poll, 0, 50)
	}

	if err := producer.Produce(rw, payload); err != nil {
		panic(err) // let the recovery middleware deal with this
	}
}
