// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/wunari/easypoll-backend/docs/models"
)

// UpdatePollByIDOKCode is the HTTP code returned for type UpdatePollByIDOK
const UpdatePollByIDOKCode int = 200

/*UpdatePollByIDOK Poll updated

swagger:response updatePollByIdOK
*/
type UpdatePollByIDOK struct {

	/*
	  In: Body
	*/
	Payload *models.Poll `json:"body,omitempty"`
}

// NewUpdatePollByIDOK creates UpdatePollByIDOK with default headers values
func NewUpdatePollByIDOK() *UpdatePollByIDOK {

	return &UpdatePollByIDOK{}
}

// WithPayload adds the payload to the update poll by Id o k response
func (o *UpdatePollByIDOK) WithPayload(payload *models.Poll) *UpdatePollByIDOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the update poll by Id o k response
func (o *UpdatePollByIDOK) SetPayload(payload *models.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *UpdatePollByIDOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// UpdatePollByIDBadRequestCode is the HTTP code returned for type UpdatePollByIDBadRequest
const UpdatePollByIDBadRequestCode int = 400

/*UpdatePollByIDBadRequest Invalid input

swagger:response updatePollByIdBadRequest
*/
type UpdatePollByIDBadRequest struct {
}

// NewUpdatePollByIDBadRequest creates UpdatePollByIDBadRequest with default headers values
func NewUpdatePollByIDBadRequest() *UpdatePollByIDBadRequest {

	return &UpdatePollByIDBadRequest{}
}

// WriteResponse to the client
func (o *UpdatePollByIDBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// UpdatePollByIDNotFoundCode is the HTTP code returned for type UpdatePollByIDNotFound
const UpdatePollByIDNotFoundCode int = 404

/*UpdatePollByIDNotFound Resource not found

swagger:response updatePollByIdNotFound
*/
type UpdatePollByIDNotFound struct {
}

// NewUpdatePollByIDNotFound creates UpdatePollByIDNotFound with default headers values
func NewUpdatePollByIDNotFound() *UpdatePollByIDNotFound {

	return &UpdatePollByIDNotFound{}
}

// WriteResponse to the client
func (o *UpdatePollByIDNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// UpdatePollByIDUnprocessableEntityCode is the HTTP code returned for type UpdatePollByIDUnprocessableEntity
const UpdatePollByIDUnprocessableEntityCode int = 422

/*UpdatePollByIDUnprocessableEntity Missing required fields

swagger:response updatePollByIdUnprocessableEntity
*/
type UpdatePollByIDUnprocessableEntity struct {
}

// NewUpdatePollByIDUnprocessableEntity creates UpdatePollByIDUnprocessableEntity with default headers values
func NewUpdatePollByIDUnprocessableEntity() *UpdatePollByIDUnprocessableEntity {

	return &UpdatePollByIDUnprocessableEntity{}
}

// WriteResponse to the client
func (o *UpdatePollByIDUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
