// Code generated by go-swagger; DO NOT EDIT.

/*
Package restapi EasyPoll
This is the oficial documentation for the EasyPoll API. If you have any problems or requests, please contact us on GitHub.


    Schemes:
      http
    Host: localhost
    BasePath: /v1
    Version: 1.0.0
    Contact: <noreply@easypoll.com.br>

    Consumes:
    - application/json

    Produces:
    - application/json

swagger:meta
*/
package restapi
