// Code generated by go-swagger; DO NOT EDIT.

package poll

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/wunari/easypoll-backend/models"
)

// CreatePollOKCode is the HTTP code returned for type CreatePollOK
const CreatePollOKCode int = 200

/*CreatePollOK Poll created

swagger:response createPollOK
*/
type CreatePollOK struct {

	/*
	  In: Body
	*/
	Payload *models.Poll `json:"body,omitempty"`
}

// NewCreatePollOK creates CreatePollOK with default headers values
func NewCreatePollOK() *CreatePollOK {

	return &CreatePollOK{}
}

// WithPayload adds the payload to the create poll o k response
func (o *CreatePollOK) WithPayload(payload *models.Poll) *CreatePollOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the create poll o k response
func (o *CreatePollOK) SetPayload(payload *models.Poll) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *CreatePollOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// CreatePollBadRequestCode is the HTTP code returned for type CreatePollBadRequest
const CreatePollBadRequestCode int = 400

/*CreatePollBadRequest Invalid input

swagger:response createPollBadRequest
*/
type CreatePollBadRequest struct {
}

// NewCreatePollBadRequest creates CreatePollBadRequest with default headers values
func NewCreatePollBadRequest() *CreatePollBadRequest {

	return &CreatePollBadRequest{}
}

// WriteResponse to the client
func (o *CreatePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(400)
}

// CreatePollUnprocessableEntityCode is the HTTP code returned for type CreatePollUnprocessableEntity
const CreatePollUnprocessableEntityCode int = 422

/*CreatePollUnprocessableEntity Missing required fields

swagger:response createPollUnprocessableEntity
*/
type CreatePollUnprocessableEntity struct {
}

// NewCreatePollUnprocessableEntity creates CreatePollUnprocessableEntity with default headers values
func NewCreatePollUnprocessableEntity() *CreatePollUnprocessableEntity {

	return &CreatePollUnprocessableEntity{}
}

// WriteResponse to the client
func (o *CreatePollUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
