// Code generated by go-swagger; DO NOT EDIT.

package vote

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	models "github.com/wunari/easypoll-backend/docs/models"
)

// AddVotePollNoContentCode is the HTTP code returned for type AddVotePollNoContent
const AddVotePollNoContentCode int = 204

/*AddVotePollNoContent Vote(s) added

swagger:response addVotePollNoContent
*/
type AddVotePollNoContent struct {
}

// NewAddVotePollNoContent creates AddVotePollNoContent with default headers values
func NewAddVotePollNoContent() *AddVotePollNoContent {

	return &AddVotePollNoContent{}
}

// WriteResponse to the client
func (o *AddVotePollNoContent) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(204)
}

// AddVotePollBadRequestCode is the HTTP code returned for type AddVotePollBadRequest
const AddVotePollBadRequestCode int = 400

/*AddVotePollBadRequest Invalid input

swagger:response addVotePollBadRequest
*/
type AddVotePollBadRequest struct {

	/*
	  In: Body
	*/
	Payload *models.Error `json:"body,omitempty"`
}

// NewAddVotePollBadRequest creates AddVotePollBadRequest with default headers values
func NewAddVotePollBadRequest() *AddVotePollBadRequest {

	return &AddVotePollBadRequest{}
}

// WithPayload adds the payload to the add vote poll bad request response
func (o *AddVotePollBadRequest) WithPayload(payload *models.Error) *AddVotePollBadRequest {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the add vote poll bad request response
func (o *AddVotePollBadRequest) SetPayload(payload *models.Error) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *AddVotePollBadRequest) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(400)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

// AddVotePollNotFoundCode is the HTTP code returned for type AddVotePollNotFound
const AddVotePollNotFoundCode int = 404

/*AddVotePollNotFound Resource not found

swagger:response addVotePollNotFound
*/
type AddVotePollNotFound struct {
}

// NewAddVotePollNotFound creates AddVotePollNotFound with default headers values
func NewAddVotePollNotFound() *AddVotePollNotFound {

	return &AddVotePollNotFound{}
}

// WriteResponse to the client
func (o *AddVotePollNotFound) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(404)
}

// AddVotePollUnprocessableEntityCode is the HTTP code returned for type AddVotePollUnprocessableEntity
const AddVotePollUnprocessableEntityCode int = 422

/*AddVotePollUnprocessableEntity Missing required fields

swagger:response addVotePollUnprocessableEntity
*/
type AddVotePollUnprocessableEntity struct {
}

// NewAddVotePollUnprocessableEntity creates AddVotePollUnprocessableEntity with default headers values
func NewAddVotePollUnprocessableEntity() *AddVotePollUnprocessableEntity {

	return &AddVotePollUnprocessableEntity{}
}

// WriteResponse to the client
func (o *AddVotePollUnprocessableEntity) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.Header().Del(runtime.HeaderContentType) //Remove Content-Type on empty responses

	rw.WriteHeader(422)
}
