// Code generated by go-swagger; DO NOT EDIT.

package vote

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime/middleware"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewAddVotePollParams creates a new AddVotePollParams object
// no default values defined in spec.
func NewAddVotePollParams() AddVotePollParams {

	return AddVotePollParams{}
}

// AddVotePollParams contains all the bound params for the add vote poll operation
// typically these are obtained from a http.Request
//
// swagger:parameters addVotePoll
type AddVotePollParams struct {

	// HTTP Request Object
	HTTPRequest *http.Request `json:"-"`

	/*The id of the answer
	  Required: true
	  In: path
	*/
	AnswerID int64
	/*The id of the poll
	  Required: true
	  In: path
	*/
	ID float64
}

// BindRequest both binds and validates a request, it assumes that complex things implement a Validatable(strfmt.Registry) error interface
// for simple values it will use straight method calls.
//
// To ensure default values, the struct must have been initialized with NewAddVotePollParams() beforehand.
func (o *AddVotePollParams) BindRequest(r *http.Request, route *middleware.MatchedRoute) error {
	var res []error

	o.HTTPRequest = r

	rAnswerID, rhkAnswerID, _ := route.Params.GetOK("answerId")
	if err := o.bindAnswerID(rAnswerID, rhkAnswerID, route.Formats); err != nil {
		res = append(res, err)
	}

	rID, rhkID, _ := route.Params.GetOK("id")
	if err := o.bindID(rID, rhkID, route.Formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindAnswerID binds and validates parameter AnswerID from path.
func (o *AddVotePollParams) bindAnswerID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertInt64(raw)
	if err != nil {
		return errors.InvalidType("answerId", "path", "int64", raw)
	}
	o.AnswerID = value

	return nil
}

// bindID binds and validates parameter ID from path.
func (o *AddVotePollParams) bindID(rawData []string, hasKey bool, formats strfmt.Registry) error {
	var raw string
	if len(rawData) > 0 {
		raw = rawData[len(rawData)-1]
	}

	// Required: true
	// Parameter is provided by construction from the route

	value, err := swag.ConvertFloat64(raw)
	if err != nil {
		return errors.InvalidType("id", "path", "float64", raw)
	}
	o.ID = value

	return nil
}
