// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"net/http"
	"strings"

	errors "github.com/go-openapi/errors"
	loads "github.com/go-openapi/loads"
	runtime "github.com/go-openapi/runtime"
	middleware "github.com/go-openapi/runtime/middleware"
	security "github.com/go-openapi/runtime/security"
	spec "github.com/go-openapi/spec"
	strfmt "github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/wunari/easypoll-backend/docs/restapi/operations/auth"
	"github.com/wunari/easypoll-backend/docs/restapi/operations/poll"
	"github.com/wunari/easypoll-backend/docs/restapi/operations/vote"

	models "github.com/wunari/easypoll-backend/docs/models"
)

// NewEasypollAPI creates a new Easypoll instance
func NewEasypollAPI(spec *loads.Document) *EasypollAPI {
	return &EasypollAPI{
		handlers:            make(map[string]map[string]http.Handler),
		formats:             strfmt.Default,
		defaultConsumes:     "application/json",
		defaultProduces:     "application/json",
		customConsumers:     make(map[string]runtime.Consumer),
		customProducers:     make(map[string]runtime.Producer),
		ServerShutdown:      func() {},
		spec:                spec,
		ServeError:          errors.ServeError,
		BasicAuthenticator:  security.BasicAuth,
		APIKeyAuthenticator: security.APIKeyAuth,
		BearerAuthenticator: security.BearerAuth,
		JSONConsumer:        runtime.JSONConsumer(),
		JSONProducer:        runtime.JSONProducer(),
		VoteAddVotePollHandler: vote.AddVotePollHandlerFunc(func(params vote.AddVotePollParams) middleware.Responder {
			return middleware.NotImplemented("operation VoteAddVotePoll has not yet been implemented")
		}),
		PollCreatePollHandler: poll.CreatePollHandlerFunc(func(params poll.CreatePollParams) middleware.Responder {
			return middleware.NotImplemented("operation PollCreatePoll has not yet been implemented")
		}),
		PollDeletePollByIDHandler: poll.DeletePollByIDHandlerFunc(func(params poll.DeletePollByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PollDeletePollByID has not yet been implemented")
		}),
		AuthGetAuthenticatedUserHandler: auth.GetAuthenticatedUserHandlerFunc(func(params auth.GetAuthenticatedUserParams, principal *models.User) middleware.Responder {
			return middleware.NotImplemented("operation AuthGetAuthenticatedUser has not yet been implemented")
		}),
		PollGetPollByIDHandler: poll.GetPollByIDHandlerFunc(func(params poll.GetPollByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PollGetPollByID has not yet been implemented")
		}),
		PollGetPollsHandler: poll.GetPollsHandlerFunc(func(params poll.GetPollsParams) middleware.Responder {
			return middleware.NotImplemented("operation PollGetPolls has not yet been implemented")
		}),
		AuthLoginUserHandler: auth.LoginUserHandlerFunc(func(params auth.LoginUserParams) middleware.Responder {
			return middleware.NotImplemented("operation AuthLoginUser has not yet been implemented")
		}),
		PollPatchPollByIDHandler: poll.PatchPollByIDHandlerFunc(func(params poll.PatchPollByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PollPatchPollByID has not yet been implemented")
		}),
		AuthRegisterUserHandler: auth.RegisterUserHandlerFunc(func(params auth.RegisterUserParams) middleware.Responder {
			return middleware.NotImplemented("operation AuthRegisterUser has not yet been implemented")
		}),
		PollUpdatePollByIDHandler: poll.UpdatePollByIDHandlerFunc(func(params poll.UpdatePollByIDParams) middleware.Responder {
			return middleware.NotImplemented("operation PollUpdatePollByID has not yet been implemented")
		}),

		// Applies when the "Authorization" header is set
		BearerAuth: func(token string) (*models.User, error) {
			return nil, errors.NotImplemented("api key auth (Bearer) Authorization from header param [Authorization] has not yet been implemented")
		},

		// default authorizer is authorized meaning no requests are blocked
		APIAuthorizer: security.Authorized(),
	}
}

/*EasypollAPI This is the oficial documentation for the EasyPoll API. If you have any problems or requests, please contact us on GitHub. */
type EasypollAPI struct {
	spec            *loads.Document
	context         *middleware.Context
	handlers        map[string]map[string]http.Handler
	formats         strfmt.Registry
	customConsumers map[string]runtime.Consumer
	customProducers map[string]runtime.Producer
	defaultConsumes string
	defaultProduces string
	Middleware      func(middleware.Builder) http.Handler

	// BasicAuthenticator generates a runtime.Authenticator from the supplied basic auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BasicAuthenticator func(security.UserPassAuthentication) runtime.Authenticator
	// APIKeyAuthenticator generates a runtime.Authenticator from the supplied token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	APIKeyAuthenticator func(string, string, security.TokenAuthentication) runtime.Authenticator
	// BearerAuthenticator generates a runtime.Authenticator from the supplied bearer token auth function.
	// It has a default implementation in the security package, however you can replace it for your particular usage.
	BearerAuthenticator func(string, security.ScopedTokenAuthentication) runtime.Authenticator

	// JSONConsumer registers a consumer for a "application/json" mime type
	JSONConsumer runtime.Consumer

	// JSONProducer registers a producer for a "application/json" mime type
	JSONProducer runtime.Producer

	// BearerAuth registers a function that takes a token and returns a principal
	// it performs authentication based on an api key Authorization provided in the header
	BearerAuth func(string) (*models.User, error)

	// APIAuthorizer provides access control (ACL/RBAC/ABAC) by providing access to the request and authenticated principal
	APIAuthorizer runtime.Authorizer

	// VoteAddVotePollHandler sets the operation handler for the add vote poll operation
	VoteAddVotePollHandler vote.AddVotePollHandler
	// PollCreatePollHandler sets the operation handler for the create poll operation
	PollCreatePollHandler poll.CreatePollHandler
	// PollDeletePollByIDHandler sets the operation handler for the delete poll by Id operation
	PollDeletePollByIDHandler poll.DeletePollByIDHandler
	// AuthGetAuthenticatedUserHandler sets the operation handler for the get authenticated user operation
	AuthGetAuthenticatedUserHandler auth.GetAuthenticatedUserHandler
	// PollGetPollByIDHandler sets the operation handler for the get poll by Id operation
	PollGetPollByIDHandler poll.GetPollByIDHandler
	// PollGetPollsHandler sets the operation handler for the get polls operation
	PollGetPollsHandler poll.GetPollsHandler
	// AuthLoginUserHandler sets the operation handler for the login user operation
	AuthLoginUserHandler auth.LoginUserHandler
	// PollPatchPollByIDHandler sets the operation handler for the patch poll by Id operation
	PollPatchPollByIDHandler poll.PatchPollByIDHandler
	// AuthRegisterUserHandler sets the operation handler for the register user operation
	AuthRegisterUserHandler auth.RegisterUserHandler
	// PollUpdatePollByIDHandler sets the operation handler for the update poll by Id operation
	PollUpdatePollByIDHandler poll.UpdatePollByIDHandler

	// ServeError is called when an error is received, there is a default handler
	// but you can set your own with this
	ServeError func(http.ResponseWriter, *http.Request, error)

	// ServerShutdown is called when the HTTP(S) server is shut down and done
	// handling all active connections and does not accept connections any more
	ServerShutdown func()

	// Custom command line argument groups with their descriptions
	CommandLineOptionsGroups []swag.CommandLineOptionsGroup

	// User defined logger function.
	Logger func(string, ...interface{})
}

// SetDefaultProduces sets the default produces media type
func (o *EasypollAPI) SetDefaultProduces(mediaType string) {
	o.defaultProduces = mediaType
}

// SetDefaultConsumes returns the default consumes media type
func (o *EasypollAPI) SetDefaultConsumes(mediaType string) {
	o.defaultConsumes = mediaType
}

// SetSpec sets a spec that will be served for the clients.
func (o *EasypollAPI) SetSpec(spec *loads.Document) {
	o.spec = spec
}

// DefaultProduces returns the default produces media type
func (o *EasypollAPI) DefaultProduces() string {
	return o.defaultProduces
}

// DefaultConsumes returns the default consumes media type
func (o *EasypollAPI) DefaultConsumes() string {
	return o.defaultConsumes
}

// Formats returns the registered string formats
func (o *EasypollAPI) Formats() strfmt.Registry {
	return o.formats
}

// RegisterFormat registers a custom format validator
func (o *EasypollAPI) RegisterFormat(name string, format strfmt.Format, validator strfmt.Validator) {
	o.formats.Add(name, format, validator)
}

// Validate validates the registrations in the EasypollAPI
func (o *EasypollAPI) Validate() error {
	var unregistered []string

	if o.JSONConsumer == nil {
		unregistered = append(unregistered, "JSONConsumer")
	}

	if o.JSONProducer == nil {
		unregistered = append(unregistered, "JSONProducer")
	}

	if o.BearerAuth == nil {
		unregistered = append(unregistered, "AuthorizationAuth")
	}

	if o.VoteAddVotePollHandler == nil {
		unregistered = append(unregistered, "vote.AddVotePollHandler")
	}

	if o.PollCreatePollHandler == nil {
		unregistered = append(unregistered, "poll.CreatePollHandler")
	}

	if o.PollDeletePollByIDHandler == nil {
		unregistered = append(unregistered, "poll.DeletePollByIDHandler")
	}

	if o.AuthGetAuthenticatedUserHandler == nil {
		unregistered = append(unregistered, "auth.GetAuthenticatedUserHandler")
	}

	if o.PollGetPollByIDHandler == nil {
		unregistered = append(unregistered, "poll.GetPollByIDHandler")
	}

	if o.PollGetPollsHandler == nil {
		unregistered = append(unregistered, "poll.GetPollsHandler")
	}

	if o.AuthLoginUserHandler == nil {
		unregistered = append(unregistered, "auth.LoginUserHandler")
	}

	if o.PollPatchPollByIDHandler == nil {
		unregistered = append(unregistered, "poll.PatchPollByIDHandler")
	}

	if o.AuthRegisterUserHandler == nil {
		unregistered = append(unregistered, "auth.RegisterUserHandler")
	}

	if o.PollUpdatePollByIDHandler == nil {
		unregistered = append(unregistered, "poll.UpdatePollByIDHandler")
	}

	if len(unregistered) > 0 {
		return fmt.Errorf("missing registration: %s", strings.Join(unregistered, ", "))
	}

	return nil
}

// ServeErrorFor gets a error handler for a given operation id
func (o *EasypollAPI) ServeErrorFor(operationID string) func(http.ResponseWriter, *http.Request, error) {
	return o.ServeError
}

// AuthenticatorsFor gets the authenticators for the specified security schemes
func (o *EasypollAPI) AuthenticatorsFor(schemes map[string]spec.SecurityScheme) map[string]runtime.Authenticator {

	result := make(map[string]runtime.Authenticator)
	for name := range schemes {
		switch name {

		case "Bearer":

			scheme := schemes[name]
			result[name] = o.APIKeyAuthenticator(scheme.Name, scheme.In, func(token string) (interface{}, error) {
				return o.BearerAuth(token)
			})

		}
	}
	return result

}

// Authorizer returns the registered authorizer
func (o *EasypollAPI) Authorizer() runtime.Authorizer {

	return o.APIAuthorizer

}

// ConsumersFor gets the consumers for the specified media types
func (o *EasypollAPI) ConsumersFor(mediaTypes []string) map[string]runtime.Consumer {

	result := make(map[string]runtime.Consumer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONConsumer

		}

		if c, ok := o.customConsumers[mt]; ok {
			result[mt] = c
		}
	}
	return result

}

// ProducersFor gets the producers for the specified media types
func (o *EasypollAPI) ProducersFor(mediaTypes []string) map[string]runtime.Producer {

	result := make(map[string]runtime.Producer)
	for _, mt := range mediaTypes {
		switch mt {

		case "application/json":
			result["application/json"] = o.JSONProducer

		}

		if p, ok := o.customProducers[mt]; ok {
			result[mt] = p
		}
	}
	return result

}

// HandlerFor gets a http.Handler for the provided operation method and path
func (o *EasypollAPI) HandlerFor(method, path string) (http.Handler, bool) {
	if o.handlers == nil {
		return nil, false
	}
	um := strings.ToUpper(method)
	if _, ok := o.handlers[um]; !ok {
		return nil, false
	}
	if path == "/" {
		path = ""
	}
	h, ok := o.handlers[um][path]
	return h, ok
}

// Context returns the middleware context for the easypoll API
func (o *EasypollAPI) Context() *middleware.Context {
	if o.context == nil {
		o.context = middleware.NewRoutableContext(o.spec, o, nil)
	}

	return o.context
}

func (o *EasypollAPI) initHandlerCache() {
	o.Context() // don't care about the result, just that the initialization happened

	if o.handlers == nil {
		o.handlers = make(map[string]map[string]http.Handler)
	}

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/polls/{id}/votes"] = vote.NewAddVotePoll(o.context, o.VoteAddVotePollHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/polls"] = poll.NewCreatePoll(o.context, o.PollCreatePollHandler)

	if o.handlers["DELETE"] == nil {
		o.handlers["DELETE"] = make(map[string]http.Handler)
	}
	o.handlers["DELETE"]["/polls/{id}"] = poll.NewDeletePollByID(o.context, o.PollDeletePollByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/user"] = auth.NewGetAuthenticatedUser(o.context, o.AuthGetAuthenticatedUserHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/polls/{id}"] = poll.NewGetPollByID(o.context, o.PollGetPollByIDHandler)

	if o.handlers["GET"] == nil {
		o.handlers["GET"] = make(map[string]http.Handler)
	}
	o.handlers["GET"]["/polls"] = poll.NewGetPolls(o.context, o.PollGetPollsHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/login"] = auth.NewLoginUser(o.context, o.AuthLoginUserHandler)

	if o.handlers["PATCH"] == nil {
		o.handlers["PATCH"] = make(map[string]http.Handler)
	}
	o.handlers["PATCH"]["/polls/{id}"] = poll.NewPatchPollByID(o.context, o.PollPatchPollByIDHandler)

	if o.handlers["POST"] == nil {
		o.handlers["POST"] = make(map[string]http.Handler)
	}
	o.handlers["POST"]["/register"] = auth.NewRegisterUser(o.context, o.AuthRegisterUserHandler)

	if o.handlers["PUT"] == nil {
		o.handlers["PUT"] = make(map[string]http.Handler)
	}
	o.handlers["PUT"]["/polls/{id}"] = poll.NewUpdatePollByID(o.context, o.PollUpdatePollByIDHandler)

}

// Serve creates a http handler to serve the API over HTTP
// can be used directly in http.ListenAndServe(":8000", api.Serve(nil))
func (o *EasypollAPI) Serve(builder middleware.Builder) http.Handler {
	o.Init()

	if o.Middleware != nil {
		return o.Middleware(builder)
	}
	return o.context.APIHandler(builder)
}

// Init allows you to just initialize the handler cache, you can then recompose the middleware as you see fit
func (o *EasypollAPI) Init() {
	if len(o.handlers) == 0 {
		o.initHandlerCache()
	}
}

// RegisterConsumer allows you to add (or override) a consumer for a media type.
func (o *EasypollAPI) RegisterConsumer(mediaType string, consumer runtime.Consumer) {
	o.customConsumers[mediaType] = consumer
}

// RegisterProducer allows you to add (or override) a producer for a media type.
func (o *EasypollAPI) RegisterProducer(mediaType string, producer runtime.Producer) {
	o.customProducers[mediaType] = producer
}
